                            <div class="span-22 last prepend-1 append-1">
                                <h1>Enter your author name and password below.</h1>
                                <div class="box">
                                <?php
                                    if ($this->failedValidation) {
                                        echo '<p>Some problems were detected with the submitted form.</p>';
                                    }

                                    if ($this->failedAuthentication) {
                                        echo '<p>Sorry, but the credentials supplied could not be authenticated. Please try again.</p>';
                                    }
                                    echo $this->loginForm;
                                ?>
                                </div>
                            </div>

