        </div><!--#content-->
    </div>
        </div><!--#container-->
        <div id="footercontainer" class="clearfix">
            <div id="footer" class="span-24">
                <div class="footer_links span-24">
                    <div id="recent" class="span-7 prepend-1 clear">
                        <h4>Recent Blog Posts</h4>
                        <ul class="clear">
                            <?php echo $this->partialLoop('partials/_footerblogs.phtml', $this->footer_blogs) ?>
                        </ul>
                       
                    </div>
                   
                </div>

            </div>
        </div><!--#footercontainer-->
        
  </body>

</html>