        </section><!--#content-->        
        <footer class="span-24">
            <nav class="span-7 prepend-1 clear">
                <h4>Recent Blog Posts</h4>
                <ul class="clear">
                    <?php echo $this->partialLoop('partials/_footerblogs.phtml', $this->footer_blogs) ?>
                </ul>
            </nav>
        </footer><!--#footercontainer-->
        </div><!--#container-->
  </body>

</html>