                                        <article class="<?php print ($this->partialCounter % 2 == 0) ? 'even' : ''; ?> comments">
                                            
                                            <header>
                                                <time><?php echo date("F jS Y", $this->published_date) ?></time>,&nbsp;
                                                <?php if ($this->url != ''): ?>
                                                <a href="<?php echo $this->url ?>" target="_blank">
                                                    <?php echo $this->username . ' says:'; ?>
                                                </a>
                                                <?php else: ?>
                                                    <?php echo $this->username . ' says:'; ?>
                                                <?php endif; ?>
                                            </header>
                                            
                                            
                                            <?php echo $this->comment ?>
                                        </article>