                                        <dl class="<?php print ($this->partialCounter % 2 == 0) ? 'even' : ''; ?> comments all-corners-5">
                                            <dt>
                                                <?php if ($this->url != ''): ?>
                                                <a href="<?php echo $this->url ?>" target="_blank">
                                                    <?php echo $this->username . ' says:'; ?>
                                                </a>
                                                <?php else: ?>
                                                    <?php echo $this->username . ' says:'; ?>
                                                <?php endif; ?>
                                                <span class="commentdate"><?php echo date("F jS Y", $this->published_date) ?></span>
                                            </dt>
                                            <dd class="comments"><?php echo $this->comment ?></dd>
                                        </dl>