                                    <?php if (!$this->hide) { ?>
                                   
                                        <header>
                                            <a href="<?php echo $this->entryUrl(array('id'=>$this->id,'title'=>$this->title)) . '#comment_form'?>"  title="Leave a comment">
                                                <span class=comments><?php echo $this->comments->total ?></span>
                                            </a>
                                            <a href="<?php echo $this->entryUrl(array('id'=>$this->id,'title'=>$this->title)) ?>">
                                                <h2 class="blog-h2"><?php echo $this->escape($this->title) ?></h2>
                                            </a>
                                        </header>
                                        <time class="posted">Posted: <?php echo date("F jS Y", $this->published_date) ?></time>
                                        
                                        <?php echo $this->content ?>
                                        <?php if(!empty($this->extended_content)): ?>
                                            <a href="<?php echo $this->entryUrl(array('id'=>$this->id,'title'=>$this->title)) ?>">Continue reading: <?php echo $this->escape($this->title) ?></a>
                                        <?php endif; ?>
                                       
                                        <?php if ($this->tags): ?>
                                        <footer>Tags: <?php echo $this->partialLoop('partials/_tags.phtml', $this->tags) ?></footer>
                                        <?php endif ?>
                                  
                                    <?php } ?>