                            <div class="main-content span-22 last prepend-1 append-1">
                                <h1 class="top-corners-10">Add new blog</h1>
                                <div class="box bottom-corners-10">
                                <?php
                                    if ($this->failedValidation) {
                                        echo '<h2>Some problems were detected with the submitted form.</h2>';
                                    }

                                    if ($this->entrySaved) {
                                        echo '<h2>New entry saved</h2>';
                                    }

                                    echo $this->entryForm;
                                ?>
                                </div>
                            </div>