                            <section class="span-22 last prepend-1 append-1">
                                <header>
                                    <h1>
                                        <?php echo $this->heading.'<a href="'.$this->entryUrl(array('id'=>$this->entry->id,'title'=>$this->entry->title)).'">'.$this->entry->title.'</a>'?>
                                    </h1>
                                </header>
                                <div class="box">
                                <?php
                                    if ($this->failedValidation) {
                                        echo '<h2>Some problems were detected with the submitted form.</h2>';
                                    }

                                    if ($this->entrySaved) {
                                        echo '<h2>Entry saved</h2>';
                                    }

                                    if ($this->failedFind) {
                                        echo '<h2>The entry could not be found in the database.</h2>';
                                    }

                                    echo '<a href="/admin">Back to Admin Index</a>';

                                    echo $this->entryForm;
                                ?>
                                </div>
                            </section>


