                            <section class="span-14 prepend-1 append-1">
                                <header>
                                    <h1>Zend Framework Blog</h1>
                                    <?php if($this->message) echo "<h2 class=\"bloglistheader\">$this->message</h2>" ?>
                                    <?php if($this->tag) echo "<h2 class=\"bloglistheader\">Posts tagged <i>$this->tag</i></h2>" ?>
                                </header>
                                <article class="box">
                                    <?php echo $this->partialLoop('partials/_entry.phtml', $this->blogs) ?>
                                </article>
                            </section>

                            <aside class="span-8 last">
                                <div class="box">
                                    <header>
                                        <h2>More on...</h2>
                                    </header>
                                    <?php echo $this->cloud ?>
                                </div>
                                <div class="box">
                                    <header>
                                      <h2>Want a regular dose?</h2>
                                    </header>
                                    <div id="subscriberform">
                                        <?php echo $this->subscriberform ?>
                                    </div>
                                </div>
                            </aside>


                        