                            <section class="span-14 prepend-1 append-1">
                                <header>
                                    <h1>Zend Framework Blog</h1>
                                </header>
                                <article class="box clearfix">
                                    <?php echo $this->partial('partials/_entryextended.phtml', $this->blog) ?>
                                    <!--Comment form-->
                                    <a name="comment_form"></a>
                                    <section>
                                        <header>
                                            <h2>Leave a comment</h2>
                                        </header>                                    
                                        <?php echo $this->form ?>
                                    </section>
                                </article>
                            </section>

                            <?php include_once 'blog_side.phtml'; ?>